### ISSUE TITLE
Proof sending to chain is failing with "insufficient funds" error

### ISSUE THREAD

**Issue by simonerom** [iotexproject/w3bstream#26]
After following the README instructions I found my node is failing for me with the `send transaction failed: insufficient funds for gas * price + value` error. However, I've used a private key that has funds on the IoTeX testnet (>1800 IOTX).

![img_v3_0251_76a6dcf9-e711-42fb-a4fb-cd2bcce2407h](https://github.com/machinefi/w3bstream-mainnet/assets/11096047/b47564b5-3953-4cd0-8b9a-d6087abdd1b8)

Can we have some additional log about the CHAIN_ENDPOINT configuration, the actual address the proof is being sent to and estimated gas in the error message?

**Comment by huangzhiran** [comment]
the EstimateGas always return err  "execution simulation failed: status = 106". I will change to hardcode gaslimit currently

**Comment by huangzhiran** [comment]
@simonerom  the gas error has been fixed
