### ISSUE TITLE
fail to donwload wsctl

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/w3bstream#31]
Environment: Ubuntu 22
 > ./sprout$ curl https://raw.githubusercontent.com/machinefi/sprout/main/scripts/install_wsctl.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'raw.githubusercontent.com'
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Another issue when executing the script directly
> bash install_wsctl.sh
Download URL not found for wsctl-linux-amd64

**Comment by huangzhiran** [comment]
<img width="734" alt="截屏2023-11-14 17 01 42" src="https://github.com/machinefi/sprout/assets/30522704/19b29435-08ed-4875-8535-1ed6fade293c">

success on my local.

**Comment by raullenchai** [comment]
Fixed.
