### ISSUE TITLE
Provide instructions to build and run the node (without docker) for contributors

### ISSUE THREAD

**Issue by simonerom** [iotexproject/w3bstream#41]
Can you provide instructions for developers on how to setup the dev environment to contribute? How to build and run the node without Docker?

**Comment by huangzhiran** [comment]
risc0 and halo2 maybe complicated run without docker image. Is it useful just run node without Docker but run risc0  & halo2 with Docker ?

**Comment by simonerom** [comment]
I'm working on configuring the setup to facilitate convenient development and debugging in VS Code without having to generate a new Docker image every time. My plan is to provide a developer-docker-compose.yaml, where the w3bnode service is commented out. All other services (Postgres, RISC0, Halo2, etc.) will continue running with Docker Compose, but their ports will be published to the host system.

I am currently testing this setup and will update here with the results.
