### ISSUE TITLE
[BUG] test: run tests failure on M1

### ISSUE THREAD

**Issue by xhd2015** [iotexproject/w3bstream#432]
When running tests, panic would happen.

That's a famous issue caused by gomonkey, does anyone here encounter?

**Comment by hunshenshi** [comment]
what's the error? and what's the command? Can I get more Infos?
However, gomonkey does have some platform compatibility issues.

Thanks

**Comment by huangzhiran** [comment]
```bash
make unit_test
```
use this cmd to run unit test
