### ISSUE TITLE
[BUG] Support revert message log when the Dapp utilizes custom errors

### ISSUE THREAD

**Issue by simonerom** [iotexproject/w3bstream#634]
**Describe the bug**
W3bstream logs currently only display standard revert messages when a proof submission to the blockchain fails. If the Dapp uses Solidity custom errors for reverting transactions, the W3bstream logs only indicate that the transaction simulation failed with error 106, without showing the specific custom error details.

**Expected behavior**
The ioctl ws message query should return the custom error message when a blockchain transaction reverts using a Solidity custom error.

**More context**
Tx errors are currently catched with
```go
catch Error(string memory revertReason) {
            emit DataProcessed(_projectId, _proverId, msg.sender, false, revertReason);
        }
    }
```
which cannot catch a custom error, but only standard reverts.

The correct way to catch a custom error seems to be something like:
```go
catch (bytes memory reason) {
    bytes4 expectedSelector = PathRegistry.InsufficientAmountOut.selector;
    bytes4 receivedSelector = bytes4(reason);
    assertEq(expectedSelector, receivedSelector);
}
```

**Comment by ququzone** [comment]
@simonerom  Thanks for report. I have fixed use bytes message. The PR is #636
